title: <p align="center"> Rahul Madan </p>
logo: /assets/img/logo.jpeg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/rahul-madan-b3907937/">LinkedIn</a> |
  <a href="https://github.com/17rahul">GitHub</a>

  <br>
  I'm working on Search, Discovery, Machine learning & NLP related problems.
  Worked with Adobe Systems Inc at Search & Sensei team.
  Working in Search, Discover & Relavence domain since past 5 years.
  <br>
  </p>



theme: jekyll-theme-minimal
